### ISSUE TITLE
Encryption overwrites existing file

### ISSUE THREAD

**Issue by zeevox** [harens/kintercrypt#24]
**Describe the bug**
Encrypting a file causes the original to be overwritten.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try encrypting a file `test.txt`
2. See that it has been overwritten with the encrypted document

**Expected behavior**
A new file is created alongside the original, called e.g. `test.enc.txt`
If this is the intended behaviour this should be warned against. Since the user is only prompted to input the encryption password _once_, if the original is overwritten a typo could cost them the whole file.

**Desktop:**
 - OS: `Ubuntu 20.04 LTS x86_64`
 - Kernel: `5.4.0-37-generic`
 - Shell: `bash 5.0.16`
 - Kintercrypt version `v0.1`

**Comment by harens** [comment]
Thank you @ZeevoX for raising this issue

Due to various Unicode Decode Errors that result from different file types, as of https://github.com/harens/kintercrypt/commit/37fea33b89669dc183b4b54827cc086183240ac7, the file input has been temporarily removed. This commit will be added to a future release.

As a result of approaching deadlines, this process has been simplified for the time being. The user enters the text to be encrypted/decrypted into a textbox, and the result is also outputted here.

Many thanks again for bringing up the issue!
